spring:
  profiles:
    active: local
  application:
    name: "base-six-four-api"
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://178.128.255.183:80/db_base_six_four?useSSL=false&serverTimezone=CAT&allowPublicKeyRetrieval=true
    username: root
    password: 211021555
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 5
  mail:
    host: smtp.gmail.com
    port: 587
    username: lindaring.developer.tools@gmail.com
    password: wrhdwrcauyvzvxza
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true
  rabbitmq:
    host: 134.209.195.231
    queueName: stukzin.queue
    exchangeName: stukzin-exchange
    routingKey: stukzin.routingkey

logging:
  level:
    org:
      springframework:
        web: debug
      hibernate: error
    com:
      lindaring:
        base: debug

custom:
  messages:
    invalidString: Invalid string entered. Cannot convert null and empty strings.

caching:
  base64: BASE_64_CACHE

api:
  mail:
    hit:
      enabled: true
      cron: "0 59 23 1/1 * ?"
      to: "lndsimelane@gmail.com"
      subject: "Lindaring Tools Visitors Report"
      body: "<html><head><style>body{font-family:'proxima-nova','proximanova','helveticaneue','helvetica','arial',sans-serif;margin:0;padding:0;}div#header{background:#ffc107;}div#header>img{max-width:35px;float:left;margin:5px;}div#header>h1{float:left;margin:5px;padding:0;color:#fff;}.clear{clear:both;}div#content{padding:010px;}</style></head><body><div id='header'><img src='http://lindaring.com/logo.png'/><h1>Lindaring Tools</h1><div class='clear'></div></div><div id='content'><h1>Users for Today</h1><h3>#TODAYS_DATE</h3><p><strong>Visitors:</strong> #NUMBER_OF_USERS<br/><strong>Hits:</strong> #NUMBER_OF_HITS</p><p>Regards,<br/><br/>Lindaring Tools Team</p></div></body></html>"
    register:
      enabled: true
      link: "http://lindaring.com/activate?code=#ACTIVATION_CODE"
      subject: "Lindaring Tools Confirmation"
      body: "<html><head><style>body{font-family:'proxima-nova','proximanova','helveticaneue','helvetica','arial',sans-serif;margin:0;padding:0;}div#header{background:#ffc107;}div#header>img{max-width:35px;float:left;margin:5px;}div#header>h1{float:left;margin:5px;padding:0;color:#fff;}.clear{clear:both;}div#content{padding:010px;}</style></head><body><div id='header'><img src='http://lindaring.com/logo.png'/><h1>Lindaring Tools</h1><div class='clear'></div></div><div id='content'><h1>Confirm Email Address</h1><p>Humble greetings,<br/><br/>Click on the below link to confirm the validity of your email address:<br/><a href='#ACTIVATION_LINK'>#ACTIVATION_LINK</a></p><p>Regards,<br/><br/>Lindaring Tools Team</p></div></body></html>"
    approval:
      enabled: true
      to: "lndsimelane@gmail.com"
      link: "http://lindaring.com/approval?code=#APPROVAL_CODE"
      subject: "Lindaring Tools Approval"
      body: "<html><head><style>body{font-family:'proxima-nova','proximanova','helveticaneue','helvetica','arial',sans-serif;margin:0;padding:0;}div#header{background:#ffc107;}div#header>img{max-width:35px;float:left;margin:5px;}div#header>h1{float:left;margin:5px;padding:0;color: #fff;}.clear{clear:both;}div#content{padding:0 10px;}</style></head><body><div id='header'><img src='http://lindaring.com/logo.png'/><h1>Developer Tools</h1><div class='clear'></div></div><div id='content'><h1>User Request</h1><p>Hi,<br/><br/>Someone has requested to be part of the Lindaring Tools Family.</p><p>Click on the below link to approve the request:<br/><a href='#APPROVAL_LINK'>#APPROVAL_LINK</a></p><p>Regards,<br/><br/><i>Lindaring Tools Team</i></p></div></body></html>"
    welcome:
      enabled: true
      link: "http://lindaring.com/login"
      subject: "Lindaring Tools Account Approved"
      body: "<html><head><style>body {font-family: 'proxima-nova', 'proximanova', 'helveticaneue', 'helvetica', 'arial', sans-serif;margin: 0;padding: 0;}div#header {background: #ffc107;}div#header > img {max-width: 35px;float: left;margin: 5px;}div#header > h1 {float: left;margin: 5px;padding: 0;color: #fff;}.clear {clear: both;}div#content {padding: 0 10px;}</style></head><body><div id='header'><img src='http://lindaring.com/logo.png'/><h1>Developer Tools</h1><div class='clear'></div></div><div id='content'><h1>Account Approved</h1><p>Howdie Partner,<br/><br/>Great news! Your account has been approved. You may now login in.</p><p><a href='#LOGIN_LINK'>#LOGIN_LINK</a></p><p>Regards,<br/><br/><i>Lindaring Tools Team</i></p></div></body></html>"
  geolocation:
    key: 4b0842278fdc1afebd2f1f27d309a8b9
    url: http://api.ipstack.com/

security:
  jwt:
    secret: "Evd+utKk@*YWez5-([6.9hx"
    tokenPrefix: "Bearer "
    headerString: "Authorization "
    expirationTime: 86400000

---
spring:
  profiles: live

---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/db_base_six_four?useSSL=false&serverTimezone=CAT&allowPublicKeyRetrieval=true
  mail:
    host: 127.0.0.1
    port: 25

api:
  mail:
    hit:
      enabled: false
    register:
      link: "http://localhost:4200/activate?code=#ACTIVATION_CODE"
      enabled: false
    approval:
      link: "http://localhost:4200/approval?code=#APPROVAL_CODE"
      enabled: false
    welcome:
      enabled: true
      link: "http://localhost:4200/login"