logging:
  level:
    org:
      springframework:
        web: debug
      hibernate: error
    com:
      lindaring:
        base: debug

custom:
  messages:
    invalidString: Invalid string entered. Cannot convert null and empty strings.

caching:
  base64: BASE_64_CACHE

spring:
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://178.128.255.183:80/db_base_six_four?useSSL=false&serverTimezone=CAT
    username: root
    password: 211021555
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 5
  mail:
    host: smtp.gmail.com
    port: 587
    username: lindaring.developer.tools@gmail.com
    password: wrhdwrcauyvzvxza
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true

api:
  geolocation:
    key: 4b0842278fdc1afebd2f1f27d309a8b9
    url: http://api.ipstack.com/
